<a href="https://colab.research.google.com/github/Aliasgar24/SpendDNA-Transaction-Analytics/blob/main/SpendDNA_Aliasgar_Vandeliwala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SpendDNA – Your Wallet's Year-End Story



**Student Name:** Aliasgar Vandeliwala

**Project:** SpendDNA – Transaction Analytics using Python

**Tools Used:** Python, NumPy, Pandas

**Dataset:** rahul_transactions.csv

# Feature 1 – Transaction Parser

In [266]:
# Import required libraries

import pandas as pd
import numpy as np

In [267]:
# Read the dataset
df = pd.read_csv("Data set for DADS June.csv")

In [268]:
# Display the first 5 rows
df.head()

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962

In [269]:
print("Shape of the dataset:", df.shape)
print("\n")

df.info()

Shape of the dataset: (1328, 8)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1328 entries, 0 to 1327
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         1328 non-null   object
 1   Time         1328 non-null   object
 2   Description  1328 non-null   object
 3   Type         1328 non-null   object
 4   Amount       1328 non-null   object
 5   Balance      1328 non-null   float64
 6   Mode         1328 non-null   object
 7   Ref          1328 non-null   object
dtypes: float64(1), object(7)
memory usage: 83.1+ KB

In [270]:
# Missing Values

df.isnull().sum()

Date           0
Time           0
Description    0
Type           0
Amount         0
Balance        0
Mode           0
Ref            0
dtype: int64

In [271]:
# Columns

df.columns.tolist()

['Date', 'Time', 'Description', 'Type', 'Amount', 'Balance', 'Mode', 'Ref']

In [272]:
# Statistics Summary

df.describe(include='all')

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
count,1328,1328,1328,1328,1328,1328.000000,1328,1328
unique,617,832,283,3,1141,NaN,4,1307
top,2024-02-07,16:19,POS SWIGGY BANGALORE,DR,"Rs. 15,000",NaN,UPI,TXN427270
freq,6,6,30,670,5,NaN,1299,2
mean,NaN,NaN,NaN,NaN,NaN,147805.330572,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,341059.809969,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,-769127.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,-104585.750000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,151650.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,448324.250000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,720079.000000,NaN,NaN

## Cleaning the Dataset

In [273]:
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 18

In [274]:
df.drop_duplicates(inplace=True)

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (1310, 8)

In [275]:
df['Date'].head(20)

0      2024-01-01
1       01-Jan-24
2       01-Jan-24
3      2024-01-01
4     01 Jan 2024
5      2024-01-01
6      2024-01-01
7       01-Jan-24
8      2024-01-02
9        02/01/24
10       02/01/24
11      02-Jan-24
12       02/01/24
13    02 Jan 2024
14      02-Jan-24
15       02/01/24
16     2024-01-02
17       02/01/24
18      03-Jan-24
19       03/01/24
Name: Date, dtype: object

In [276]:
df['Date'] = pd.to_datetime(
    df['Date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [277]:
print("Invalid dates:", df['Date'].isna().sum())

Invalid dates: 0

In [278]:
df['Amount'].head(15)

0       ₹2462
1       50.00
2      ₹84728
3       ₹1828
4      270.00
5     Rs. 625
6     Rs. 148
7        ₹482
8     Rs. 537
9        3956
10       ₹350
11       ₹311
12     258.00
13       ₹571
14     266.00
Name: Amount, dtype: object

In [279]:
df['Amount'] = (
    df['Amount']
    .astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace('Rs.', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
)

In [280]:
df['Amount'] = pd.to_numeric(df['Amount'], errors='coerce')

In [281]:
print("Invalid Amounts:", df['Amount'].isna().sum())

Invalid Amounts: 0

In [282]:
df['Type'].value_counts()

Type
DR       662
Debit    642
CR         6
Name: count, dtype: int64

In [283]:
df['Type'] = (
    df['Type']
    .str.strip()
    .str.lower()
    .replace({
        'DR': 'debit',
        'CR': 'credit',
        'dr': 'debit',
        'cr': 'credit'
    })
)

In [284]:
df['Type'].value_counts()

Type
debit     1304
credit       6
Name: count, dtype: int64

In [285]:
df['Mode'].isnull().sum()

np.int64(0)

In [286]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1310 entries, 0 to 1327
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         1310 non-null   datetime64[ns]
 1   Time         1310 non-null   object
 2   Description  1310 non-null   object
 3   Type         1310 non-null   object
 4   Amount       1310 non-null   float64
 5   Balance      1310 non-null   float64
 6   Mode         1310 non-null   object
 7   Ref          1310 non-null   object
dtypes: datetime64[ns](1), float64(2), object(5)
memory usage: 92.1+ KB

In [287]:
df.head()

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,debit,2462.0,678275.0,UPI,TXN190872
1,2024-01-01,05:44,BHIM-BMTC,debit,50.0,681007.0,UPI,TXN143064
2,2024-01-01,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,credit,84728.0,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,debit,1828.0,-748745.0,UPI,TXN569226
4,2024-01-01,14:23,BHIM-BLINKIT,debit,270.0,680737.0,UPI,TXN968962

# Feature 2 - Vendor Extractor

In [288]:
df['Description'].nunique()

283

In [289]:
df['Description'].unique()[:50]

array(['AMAZON SELLER SVCS', 'BHIM-BMTC',
       'NEFT-TECHCRUSH LABS-SALARY MAY24', 'UPI-AMAN-8934@OKAXIS',
       'BHIM-BLINKIT', 'BHIM ZEPTO', 'UPI-UBER-2426@HDFCBANK',
       'POS SWIGGY BANGALORE', 'UPI-GROWWPAY@HDFCBANK', 'OLA ELECTRIC',
       'BMS MOVIE TICKETS', 'POS OLA-PRIME', 'SWIGGY-INSTAMART',
       'UPI-STARBUCKS@AXIS', 'UPI-THIRDWAVE@OKAXIS', 'ANI Technologies',
       'BMTC BUS PASS', 'POS TRUFFLES', 'FLIPKART INDIA',
       'POS SWIGGY-RESTAURANT', 'GROFERS INDIA P L', 'POS UBER BANGALORE',
       'BANGALORE ELEC SUPPLY', 'TWC INDIA', 'UPI-BESCOM-BILL@HDFCBANK',
       'UPI-AMAN-0816@OKAXIS', 'ROPPEN TRANSPORTATION', 'OLA CABS',
       'POS ZOMATO', 'UPI-AMAZONPAY@HDFCBANK', 'POS BLINKIT',
       'IMPS-RENT-LANDLORD-75500265', 'ZOMATO MEDIA P L',
       'UPI-ANKIT-6430@OKAXIS', 'UPI-OLACABS@HDFCBANK',
       'UPI-JIORECHARGE@PAYTM', 'UPI-CCD@HDFCBANK', 'Swiggy*Order',
       'INSTAMART BANGALORE', 'UPI-ZOMATO-LIMITED@PAYTM',
       'AVENUE SUPERMARTS', 'POS HP PETROL STATION',
       'UPI-VIKAS-6060@OKAXIS', 'POS BANGALORE RESTAURANT',
       'UPI-ZERODHA-COIN@AXIS', 'BHIM SWIGGY', 'UPI-BOOKMYSHOW@HDFCBANK',
       'BLINKIT BANGALORE', 'POS ZEPTO BANGALORE', 'UPI-DMART@OKAXIS'],
      dtype=object)

In [290]:
# Vendor Dictionary

vendor_dict = {

    "Swiggy": ["SWIGGY", "BUNDL"],

    "Zomato": ["ZOMATO"],

    "Blinkit": ["BLINKIT"],

    "Zepto": ["ZEPTO"],

    "Instamart": ["INSTAMART"],

    "Amazon": ["AMAZON", "AMZN"],

    "Flipkart": ["FLIPKART"],

    "DMart": ["DMART", "AVENUE SUPERMARTS"],

    "BigBasket": ["BIGBASKET"],

    "Uber": ["UBER"],

    "Ola": ["OLA", "ANI TECHNOLOGIES"],

    "BMTC": ["BMTC"],

    "Starbucks": ["STARBUCKS"],

    "Third Wave Coffee": ["THIRDWAVE", "TWC"],

    "Cafe Coffee Day": ["CCD"],

    "Truffles": ["TRUFFLES"],

    "Restaurant": ["RESTAURANT"],

    "BookMyShow": ["BOOKMYSHOW", "BMS"],

    "Groww": ["GROWW"],

    "Zerodha": ["ZERODHA"],

    "HP Petrol": ["HP PETROL"],

    "BESCOM": ["BESCOM", "BANGALORE ELEC"],

    "Jio": ["JIO"],

    "Rent": ["RENT"],

    "Salary": ["SALARY", "TECHCRUSH"],

    "Cash Withdrawal": ["ATM"],

    "P2P Transfer": ["AMAN", "ANKIT", "VIKAS", "PRIYA"]
}

In [291]:
def extract_vendor(description):

    description = description.upper()

    for vendor, keywords in vendor_dict.items():

        for keyword in keywords:

            if keyword in description:

                return vendor

    return "Uncategorised"

In [292]:
df["Vendor"] = df["Description"].apply(extract_vendor)

In [293]:
df["Vendor"].nunique()

28

In [294]:
df["Vendor"].value_counts()

Vendor
Uncategorised        262
Swiggy               223
Zomato               121
Ola                   87
Amazon                86
Uber                  71
Zepto                 58
Flipkart              43
Restaurant            42
Starbucks             42
Blinkit               40
BMTC                  37
DMart                 22
Instamart             20
Third Wave Coffee     20
Cash Withdrawal       17
BESCOM                15
Zerodha               14
P2P Transfer          14
BookMyShow            11
BigBasket             11
Groww                  9
HP Petrol              9
Truffles               9
Cafe Coffee Day        9
Salary                 6
Jio                    6
Rent                   6
Name: count, dtype: int64

In [295]:
df[df["Vendor"]=="Uncategorised"]["Description"].unique()

array(['GROFERS INDIA P L', 'ROPPEN TRANSPORTATION', 'UPI-RAPIDO@OKAXIS',
       'POS CAFE COFFEE DAY', 'UPI-MYNTRA@HDFCBANK', 'UPI-BWSSB@AXIS',
       'UPI-NETFLIX-MEMB@HDFCBANK', 'AIRTEL POSTPAID',
       'POS NYKAA BANGALORE', 'VI POSTPAID', 'POS BPCL PETROL PUMP',
       'POS INDIAN OIL BANGALORE', 'UPI-SPOTIFY-IN@AXIS', 'POS DINEOUT',
       'COFFEE DAY GLOBAL', 'UPI-NYKAA@AXIS', 'RAPIDO BIKE TAXI',
       'DISNEY HOTSTAR', 'POS MEGHANA FOODS', 'UPI-IOC9075@HDFCBANK',
       'FKART INTRNET', 'MYNTRA-ORDER', 'MYNTRA DESIGNS', 'POS MYNTRA',
       'POS THIRD WAVE COFFEE', 'SPOTIFY INDIA', 'NETFLIX ENTERTAINMENT',
       'FSN E-COMMERCE', 'UPI-NEHA-9795@OKAXIS', 'BIGTREE ENTERTAINMENT',
       'INNOVATIVE RETAIL', 'STAR INDIA PVT LTD', 'UPI-NEHA-5906@OKAXIS',
       'KIRANAKART TECH', 'UPI-HOTSTAR@AXIS', 'NETFLIX.COM',
       'UPI-IOC0494@HDFCBANK', 'UPI-IOC1246@HDFCBANK', 'SPOTIFY*PREMIUM',
       'BWSSB WATER BILL', 'UPI-IOC2000@HDFCBANK',
       'UPI-SNEHA-0942@OKAXIS', 'BHARTI AIRTEL LTD',
       'UPI-VI-RECHARGE@HDFCBANK', 'UPI-KARAN-5789@OKAXIS',
       'NYKAA E-RETAIL', 'UPI-IOC2115@HDFCBANK', 'VODAFONE IDEA LTD',
       'UPI-IOC5182@HDFCBANK'], dtype=object)

In [296]:
# Updated Vendor Dictionary

vendor_dict = {

    "Swiggy": ["SWIGGY", "BUNDL"],

    "Zomato": ["ZOMATO"],

    "Blinkit": ["BLINKIT", "GROFERS"],

    "Zepto": ["ZEPTO"],

    "Instamart": ["INSTAMART"],

    "Amazon": ["AMAZON", "AMZN"],

    "Flipkart": ["FLIPKART", "FKART"],

    "Myntra": ["MYNTRA"],

    "Nykaa": ["NYKAA", "FSN"],

    "DMart": ["DMART", "AVENUE SUPERMARTS"],

    "BigBasket": ["BIGBASKET", "INNOVATIVE RETAIL", "KIRANAKART"],

    "Uber": ["UBER"],

    "Rapido": ["RAPIDO", "ROPPEN"],

    "Ola": ["OLA", "ANI TECHNOLOGIES"],

    "BMTC": ["BMTC"],

    "Starbucks": ["STARBUCKS"],

    "Third Wave Coffee": ["THIRDWAVE", "TWC", "THIRD WAVE"],

    "Cafe Coffee Day": ["CCD", "COFFEE DAY"],

    "Truffles": ["TRUFFLES"],

    "Meghana Foods": ["MEGHANA"],

    "Restaurant": ["RESTAURANT", "DINEOUT"],

    "BookMyShow": ["BOOKMYSHOW", "BMS", "BIGTREE"],

    "Netflix": ["NETFLIX"],

    "Spotify": ["SPOTIFY"],

    "Hotstar": ["HOTSTAR", "STAR INDIA"],

    "Groww": ["GROWW"],

    "Zerodha": ["ZERODHA"],

    "HP Petrol": ["HP PETROL"],

    "Indian Oil": ["IOC", "INDIAN OIL"],

    "BPCL": ["BPCL"],

    "BESCOM": ["BESCOM", "BANGALORE ELEC"],

    "BWSSB": ["BWSSB"],

    "Airtel": ["AIRTEL", "BHARTI"],

    "Vi": ["VI", "VODAFONE"],

    "Jio": ["JIO"],

    "Rent": ["RENT"],

    "Salary": ["SALARY", "TECHCRUSH"],

    "Cash Withdrawal": ["ATM"],

    "P2P Transfer": [
        "AMAN",
        "ANKIT",
        "VIKAS",
        "PRIYA",
        "NEHA",
        "SNEHA",
        "KARAN"
    ]
}

In [297]:
df["Vendor"] = df["Description"].apply(extract_vendor)

In [298]:
df["Vendor"].value_counts()

Vendor
Swiggy               223
Zomato               121
Ola                   87
Amazon                86
Uber                  71
Zepto                 58
Blinkit               55
Rapido                55
Restaurant            52
Flipkart              47
Starbucks             42
BMTC                  37
BigBasket             32
Third Wave Coffee     31
Cafe Coffee Day       26
DMart                 22
Instamart             20
Myntra                20
Nykaa                 19
Cash Withdrawal       17
Indian Oil            17
BESCOM                15
P2P Transfer          14
Zerodha               14
BookMyShow            13
Hotstar               13
Vi                    12
Meghana Foods         12
Netflix               10
Groww                  9
Truffles               9
HP Petrol              9
Spotify                8
BWSSB                  8
Salary                 6
Jio                    6
Rent                   6
Airtel                 6
BPCL                   2
Name: count, dtype: int64

In [299]:
df[df["Vendor"]=="Uncategorised"]["Description"].unique()

array([], dtype=object)

# Feature 3 – Category Tagger

In [300]:
category_dict = {

    # Food Delivery
    "Swiggy": "Food Delivery",
    "Zomato": "Food Delivery",

    # Quick Commerce
    "Blinkit": "Quick Commerce",
    "Zepto": "Quick Commerce",
    "Instamart": "Quick Commerce",

    # E-Commerce
    "Amazon": "E-Commerce",
    "Flipkart": "E-Commerce",
    "Myntra": "E-Commerce",
    "Nykaa": "E-Commerce",

    # Groceries
    "DMart": "Groceries",
    "BigBasket": "Groceries",

    # Transport
    "Uber": "Transport",
    "Ola": "Transport",
    "Rapido": "Transport",
    "BMTC": "Transport",

    # Cafes
    "Starbucks": "Cafe",
    "Third Wave Coffee": "Cafe",
    "Cafe Coffee Day": "Cafe",

    # Restaurants
    "Restaurant": "Restaurants",
    "Truffles": "Restaurants",
    "Meghana Foods": "Restaurants",

    # Entertainment
    "BookMyShow": "Entertainment",

    # Subscriptions
    "Netflix": "Subscriptions",
    "Spotify": "Subscriptions",
    "Hotstar": "Subscriptions",

    # Investments
    "Groww": "Investments",
    "Zerodha": "Investments",

    # Fuel
    "HP Petrol": "Fuel",
    "Indian Oil": "Fuel",
    "BPCL": "Fuel",

    # Utilities
    "BESCOM": "Utilities",
    "BWSSB": "Utilities",
    "Airtel": "Utilities",
    "Vi": "Utilities",
    "Jio": "Utilities",

    # Salary
    "Salary": "Salary",

    # Rent
    "Rent": "Rent",

    # Transfers
    "P2P Transfer": "Personal Transfer",

    # Cash
    "Cash Withdrawal": "Cash Withdrawal"
}

In [301]:
df["Category"] = df["Vendor"].map(category_dict)

In [302]:
print("Missing Categories:", df["Category"].isna().sum())

Missing Categories: 0

In [303]:
df["Category"].value_counts()

Category
Food Delivery        344
Transport            250
E-Commerce           172
Quick Commerce       133
Cafe                  99
Restaurants           73
Groceries             54
Utilities             47
Subscriptions         31
Fuel                  28
Investments           23
Cash Withdrawal       17
Personal Transfer     14
Entertainment         13
Salary                 6
Rent                   6
Name: count, dtype: int64

In [304]:
df[["Vendor", "Category"]].head(20)

               Vendor           Category
0              Amazon         E-Commerce
1                BMTC          Transport
2              Salary             Salary
3        P2P Transfer  Personal Transfer
4             Blinkit     Quick Commerce
5               Zepto     Quick Commerce
6                Uber          Transport
7             Blinkit     Quick Commerce
8              Swiggy      Food Delivery
9               Groww        Investments
10                Ola          Transport
11         BookMyShow      Entertainment
12                Ola          Transport
13             Swiggy      Food Delivery
14          Starbucks               Cafe
15  Third Wave Coffee               Cafe
16                Ola          Transport
17               BMTC          Transport
18           Truffles        Restaurants
19           Flipkart         E-Commerce

# Feature 4 – Spending Overview

In [305]:
credit_df = df[df["Type"] == "credit"]
debit_df = df[df["Type"] == "debit"]

In [306]:
total_credit = credit_df["Amount"].sum()
total_debit = debit_df["Amount"].sum()

print(f"Total Credits : ₹{total_credit:,.2f}")
print(f"Total Debits  : ₹{total_debit:,.2f}")

Total Credits : ₹509,774.00
Total Debits  : ₹1,678,901.00

In [307]:
net_change = total_credit - total_debit

print(f"Net Change : ₹{net_change:,.2f}")

Net Change : ₹-1,169,127.00

In [308]:
savings_rate = ((total_credit - total_debit) / total_credit) * 100

print(f"Savings Rate : {savings_rate:.2f}%")

Savings Rate : -229.34%

In [309]:
print("Total Transactions :", len(df))

Total Transactions : 1310

In [310]:
top_categories = (
    debit_df
    .groupby("Category")["Amount"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

top_categories

Category
E-Commerce       603877.0
Investments      248160.0
Food Delivery    150839.0
Restaurants      117737.0
Rent             108000.0
Name: Amount, dtype: float64

In [311]:
top_vendors = (
    debit_df
    .groupby("Vendor")["Amount"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

top_vendors

Vendor
Amazon      328530.0
Zerodha     210000.0
Flipkart    177510.0
Rent        108000.0
Swiggy       95523.0
Name: Amount, dtype: float64

In [312]:
category_percentage = (
    debit_df
    .groupby("Category")["Amount"]
    .sum()
    / total_debit
) * 100

category_percentage.sort_values(ascending=False).head(10)

Category
E-Commerce        35.968589
Investments       14.781098
Food Delivery      8.984389
Restaurants        7.012742
Rent               6.432780
Fuel               5.319134
Quick Commerce     4.108640
Groceries          3.830422
Transport          3.423311
Utilities          2.780033
Name: Amount, dtype: float64

In [313]:
print("=" * 50)
print("        EXECUTIVE SUMMARY")
print("=" * 50)

print(f"Total Credits      : ₹{total_credit:,.2f}")
print(f"Total Debits       : ₹{total_debit:,.2f}")
print(f"Net Change         : ₹{net_change:,.2f}")
print(f"Savings Rate       : {savings_rate:.2f}%")
print(f"Transactions       : {len(df)}")
print(f"Unique Vendors     : {df['Vendor'].nunique()}")

print("=" * 50)

==================================================
        EXECUTIVE SUMMARY
==================================================
Total Credits      : ₹509,774.00
Total Debits       : ₹1,678,901.00
Net Change         : ₹-1,169,127.00
Savings Rate       : -229.34%
Transactions       : 1310
Unique Vendors     : 39
==================================================

# Feature 5 – Monthly Trend Analysis

In [314]:
df["Month"] = df["Date"].dt.month_name()

In [315]:
debit_df = df[df["Type"] == "debit"]

In [316]:
df[["Date", "Month"]].head()

        Date    Month
0 2024-01-01  January
1 2024-01-01  January
2 2024-01-01  January
3 2024-01-01  January
4 2024-01-01  January

In [317]:
monthly_spending = debit_df.pivot_table(
    values="Amount",
    index="Category",
    columns="Month",
    aggfunc="sum",
    fill_value=0
)

monthly_spending

Month                April  February  January      June     March      May
Category
Cafe                6564.0    4273.0   3690.0    5802.0    5448.0   5668.0
Cash Withdrawal     5500.0    5000.0   2000.0   17000.0    8000.0   8000.0
E-Commerce         69219.0   94011.0  98623.0  138033.0  108215.0  95776.0
Entertainment       2224.0     474.0   1263.0    1914.0    2418.0      0.0
Food Delivery      27756.0   23740.0  22633.0   26499.0   24803.0  25408.0
Fuel               18718.0    2079.0  30322.0    2882.0   26164.0   9138.0
Groceries          13061.0    8571.0  17649.0    7721.0    6971.0  10336.0
Investments        54126.0   15000.0  38432.0   23330.0   68644.0  48628.0
Personal Transfer    663.0    4285.0   7523.0    1541.0    2415.0   3412.0
Quick Commerce     10557.0   15177.0  11054.0    7519.0   13344.0  11329.0
Rent               18000.0   18000.0  18000.0   18000.0   18000.0  18000.0
Restaurants         7711.0   21772.0  16320.0   21335.0   28313.0  22286.0
Subscriptions       2168.0    4628.0   2767.0    3555.0    3509.0   1844.0
Transport           9284.0   10191.0  11005.0    6996.0    6857.0  13141.0
Utilities           5831.0    6870.0   9486.0   12790.0    7357.0   4340.0

In [318]:
month_order = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June"
]

monthly_spending = monthly_spending.reindex(columns=month_order, fill_value=0)

monthly_spending

Month              January  February     March    April      May      June
Category
Cafe                3690.0    4273.0    5448.0   6564.0   5668.0    5802.0
Cash Withdrawal     2000.0    5000.0    8000.0   5500.0   8000.0   17000.0
E-Commerce         98623.0   94011.0  108215.0  69219.0  95776.0  138033.0
Entertainment       1263.0     474.0    2418.0   2224.0      0.0    1914.0
Food Delivery      22633.0   23740.0   24803.0  27756.0  25408.0   26499.0
Fuel               30322.0    2079.0   26164.0  18718.0   9138.0    2882.0
Groceries          17649.0    8571.0    6971.0  13061.0  10336.0    7721.0
Investments        38432.0   15000.0   68644.0  54126.0  48628.0   23330.0
Personal Transfer   7523.0    4285.0    2415.0    663.0   3412.0    1541.0
Quick Commerce     11054.0   15177.0   13344.0  10557.0  11329.0    7519.0
Rent               18000.0   18000.0   18000.0  18000.0  18000.0   18000.0
Restaurants        16320.0   21772.0   28313.0   7711.0  22286.0   21335.0
Subscriptions       2767.0    4628.0    3509.0   2168.0   1844.0    3555.0
Transport          11005.0   10191.0    6857.0   9284.0  13141.0    6996.0
Utilities           9486.0    6870.0    7357.0   5831.0   4340.0   12790.0

In [319]:
monthly_spending["Growth (%)"] = (
    (monthly_spending["June"] - monthly_spending["January"])
    / monthly_spending["January"].replace(0, np.nan)
) * 100

In [320]:
highest_growth = monthly_spending["Growth (%)"].idxmax()
growth_value = monthly_spending.loc[highest_growth, "Growth (%)"]

print("Highest Growth Category:", highest_growth)
print(f"Growth: {growth_value:.2f}%")

Highest Growth Category: Cash Withdrawal
Growth: 750.00%

In [321]:
highest_decline = monthly_spending["Growth (%)"].idxmin()
decline_value = monthly_spending.loc[highest_decline, "Growth (%)"]

print("Highest Decline Category:", highest_decline)
print(f"Decline: {decline_value:.2f}%")

Highest Decline Category: Fuel
Decline: -90.50%

In [322]:
monthly_spending.round(2)

Month,January,February,March,April,May,June,Growth (%)
Category,,,,,,,
Cafe,3690.0,4273.0,5448.0,6564.0,5668.0,5802.0,57.24
Cash Withdrawal,2000.0,5000.0,8000.0,5500.0,8000.0,17000.0,750.00
E-Commerce,98623.0,94011.0,108215.0,69219.0,95776.0,138033.0,39.96
Entertainment,1263.0,474.0,2418.0,2224.0,0.0,1914.0,51.54
Food Delivery,22633.0,23740.0,24803.0,27756.0,25408.0,26499.0,17.08
Fuel,30322.0,2079.0,26164.0,18718.0,9138.0,2882.0,-90.50
Groceries,17649.0,8571.0,6971.0,13061.0,10336.0,7721.0,-56.25
Investments,38432.0,15000.0,68644.0,54126.0,48628.0,23330.0,-39.30
Personal Transfer,7523.0,4285.0,2415.0,663.0,3412.0,1541.0,-79.52
Quick Commerce,11054.0,15177.0,13344.0,10557.0,11329.0,7519.0,-31.98
Rent,18000.0,18000.0,18000.0,18000.0,18000.0,18000.0,0.00
Restaurants,16320.0,21772.0,28313.0,7711.0,22286.0,21335.0,30.73
Subscriptions,2767.0,4628.0,3509.0,2168.0,1844.0,3555.0,28.48
Transport,11005.0,10191.0,6857.0,9284.0,13141.0,6996.0,-36.43
Utilities,9486.0,6870.0,7357.0,5831.0,4340.0,12790.0,34.83

# Feature 6 – Time-of-Day Analysis

In [323]:
df["Hour"] = df["Time"].str[:2].astype(int)

In [324]:
df[["Time", "Hour"]].head()

    Time  Hour
0  03:11     3
1  05:44     5
2  09:35     9
3  14:07    14
4  14:23    14

In [325]:
# Hourly Spending

hourly_spending = (
    df[df["Type"] == "debit"]
    .groupby("Hour")["Amount"]
    .sum()
)

hourly_spending

Hour
0      37969.0
1      38882.0
2      20283.0
3      34868.0
4      43901.0
5      33671.0
6      55506.0
7      19938.0
8      41399.0
9      86701.0
10    140526.0
11    123389.0
12     77096.0
13    113819.0
14    121010.0
15     39647.0
16    100597.0
17     56604.0
18    101343.0
19     67848.0
20    138089.0
21     81545.0
22     55867.0
23     48403.0
Name: Amount, dtype: float64

In [326]:
peak_hour = hourly_spending.idxmax()

print("Peak Spending Hour:", peak_hour)

Peak Spending Hour: 10

In [327]:
# Category-wise Hourly Spending

category_hour = (
    df[df["Type"] == "debit"]
    .pivot_table(
        values="Amount",
        index="Category",
        columns="Hour",
        aggfunc="sum",
        fill_value=0
    )
)

category_hour

Hour,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
Category,,,,,,,,,,,,,,,,,,,,,
Cafe,872.0,549.0,0.0,316.0,0.0,0.0,179.0,480.0,2668.0,1986.0,...,1332.0,2085.0,3079.0,3552.0,2562.0,584.0,1491.0,0.0,0.0,764.0
Cash Withdrawal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4000.0,10500.0,...,1000.0,0.0,5000.0,0.0,5000.0,0.0,1000.0,1000.0,4000.0,0.0
E-Commerce,18650.0,9801.0,10246.0,14865.0,12018.0,17258.0,9249.0,10916.0,6537.0,40724.0,...,72584.0,7700.0,52046.0,35378.0,35272.0,12668.0,51190.0,35095.0,16182.0,15403.0
Entertainment,562.0,620.0,0.0,0.0,0.0,0.0,0.0,311.0,1463.0,0.0,...,0.0,0.0,1881.0,0.0,1270.0,417.0,1426.0,0.0,343.0,0.0
Food Delivery,832.0,3017.0,928.0,1702.0,2618.0,3488.0,238.0,1498.0,3737.0,5299.0,...,4236.0,7891.0,5008.0,3951.0,13587.0,17300.0,18372.0,12123.0,9283.0,4662.0
Fuel,2675.0,2048.0,0.0,676.0,2010.0,2105.0,0.0,0.0,1727.0,2283.0,...,7828.0,11937.0,9343.0,0.0,1950.0,8351.0,705.0,11845.0,0.0,1641.0
Groceries,3895.0,1536.0,2352.0,10064.0,1169.0,0.0,5265.0,0.0,2640.0,5694.0,...,3201.0,0.0,1934.0,0.0,1079.0,1248.0,3027.0,4138.0,344.0,2536.0
Investments,4883.0,15000.0,0.0,0.0,18834.0,4496.0,37717.0,0.0,0.0,4737.0,...,0.0,0.0,0.0,0.0,15000.0,4476.0,15000.0,0.0,15000.0,18628.0
Personal Transfer,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2425.0,...,1828.0,0.0,2361.0,2487.0,864.0,1295.0,2548.0,1532.0,325.0,0.0
Quick Commerce,1542.0,1402.0,1143.0,1165.0,768.0,1448.0,787.0,252.0,1625.0,6558.0,...,2774.0,3438.0,4220.0,948.0,5055.0,6992.0,6858.0,6251.0,3061.0,1669.0
Rent,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,18000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Restaurants,1411.0,960.0,1336.0,1714.0,0.0,2126.0,859.0,0.0,8037.0,702.0,...,385.0,769.0,11798.0,4094.0,10788.0,8615.0,27663.0,6348.0,2782.0,1256.0
Subscriptions,0.0,1038.0,1295.0,4029.0,4685.0,745.0,657.0,1157.0,0.0,0.0,...,1473.0,0.0,0.0,0.0,0.0,1435.0,0.0,119.0,0.0,0.0
Transport,706.0,260.0,358.0,337.0,577.0,2005.0,555.0,3924.0,4311.0,2789.0,...,2096.0,3767.0,3325.0,3751.0,3448.0,3759.0,4647.0,1622.0,1852.0,1458.0
Utilities,1941.0,2651.0,2625.0,0.0,1222.0,0.0,0.0,1400.0,4654.0,3004.0,...,4273.0,2060.0,602.0,2443.0,5468.0,708.0,4162.0,1472.0,2695.0,386.0

In [328]:
food_delivery = df[
    (df["Category"] == "Food Delivery") &
    (df["Type"] == "debit")
]

In [329]:
late_night = food_delivery[
    (food_delivery["Hour"] >= 21) |
    (food_delivery["Hour"] <= 1)
]

In [330]:
late_night_percentage = (
    len(late_night) / len(food_delivery)
) * 100

print(f"Late Night Food Delivery Orders: {late_night_percentage:.2f}%")

Late Night Food Delivery Orders: 20.64%

In [331]:
peak_hour_category = (
    df[df["Type"] == "debit"]
    .groupby("Category")["Hour"]
    .agg(lambda x: x.mode()[0])
)

peak_hour_category

Category
Cafe                 10
Cash Withdrawal       9
E-Commerce           11
Entertainment         8
Food Delivery        20
Fuel                 12
Groceries             3
Investments          10
Personal Transfer    16
Quick Commerce       19
Rent                 13
Restaurants          20
Subscriptions         4
Transport            20
Utilities             8
Name: Hour, dtype: int64

In [332]:
print("=" * 50)
print("TIME OF DAY ANALYSIS")
print("=" * 50)

print(f"Peak Spending Hour: {peak_hour}:00")
print(f"Late Night Food Delivery Orders: {late_night_percentage:.2f}%")

==================================================
TIME OF DAY ANALYSIS
==================================================
Peak Spending Hour: 10:00
Late Night Food Delivery Orders: 20.64%

# Feature 7 – Anomaly Detection

In [333]:
df["Category_Mean"] = (
    df.groupby("Category")["Amount"]
      .transform("mean")
)

In [334]:
df["Category_STD"] = (
    df.groupby("Category")["Amount"]
      .transform("std")
)

In [335]:
df["Z_Score"] = (
    (df["Amount"] - df["Category_Mean"])
    / df["Category_STD"]
)

In [336]:
anomalies = df[df["Z_Score"] > 2]

In [337]:
anomalies = anomalies.sort_values(
    by="Z_Score",
    ascending=False
)

In [338]:
anomalies[
    [
        "Date",
        "Vendor",
        "Category",
        "Amount",
        "Z_Score"
    ]
].head(10)

           Date         Vendor     Category   Amount   Z_Score
1298 2024-06-26         Amazon   E-Commerce  22008.0  4.090349
269  2024-02-07         Amazon   E-Commerce  21986.0  4.085484
414  2024-02-26     Restaurant  Restaurants   8383.0  3.884639
475  2024-03-05         Amazon   E-Commerce  19917.0  3.627956
1271 2024-06-22     Restaurant  Restaurants   7935.0  3.627582
653  2024-03-31  Meghana Foods  Restaurants   7931.0  3.625287
464  2024-03-04       Truffles  Restaurants   7441.0  3.344131
49   2024-01-07     Restaurant  Restaurants   7314.0  3.271260
450  2024-03-02         Amazon   E-Commerce  18273.0  3.264410
1079 2024-05-27       Flipkart   E-Commerce  17831.0  3.166669

In [339]:
print("Total Anomalies Detected:", len(anomalies))

Total Anomalies Detected: 30

In [340]:
print("=" * 50)
print("ANOMALY DETECTION")
print("=" * 50)

print("Total Anomalies:", len(anomalies))

print("\nTop 5 Anomalies\n")

print(
    anomalies[
        [
            "Date",
            "Vendor",
            "Category",
            "Amount",
            "Z_Score"
        ]
    ].head()
)

==================================================
ANOMALY DETECTION
==================================================
Total Anomalies: 30

Top 5 Anomalies

           Date      Vendor     Category   Amount   Z_Score
1298 2024-06-26      Amazon   E-Commerce  22008.0  4.090349
269  2024-02-07      Amazon   E-Commerce  21986.0  4.085484
414  2024-02-26  Restaurant  Restaurants   8383.0  3.884639
475  2024-03-05      Amazon   E-Commerce  19917.0  3.627956
1271 2024-06-22  Restaurant  Restaurants   7935.0  3.627582

# Feature 8 – Spending Archetype Detection

In [341]:
archetypes = []

total_debit = df[df["Type"] == "debit"]["Amount"].sum()

In [342]:
# FOODIE
food_spending = df[
    (df["Category"].isin(["Food Delivery", "Restaurants", "Cafe"])) &
    (df["Type"] == "debit")
]["Amount"].sum()

food_percentage = (food_spending / total_debit) * 100

if food_percentage > 25:
    archetypes.append("🍔 THE FOODIE")



# QUICK COMMERCE
quick_spending = df[
    (df["Category"] == "Quick Commerce") &
    (df["Type"] == "debit")
]["Amount"].sum()

quick_percentage = (quick_spending / total_debit) * 100

if quick_percentage > 15:
    archetypes.append("🛒 THE QUICK COMMERCE JUNKIE")



# SHOPAHOLIC
shopping = df[
    (df["Category"] == "E-Commerce") &
    (df["Type"] == "debit")
]["Amount"].sum()

shopping_percentage = (shopping / total_debit) * 100

if shopping_percentage > 15:
    archetypes.append("🛍️ THE SHOPAHOLIC")


# INVESTOR
investment = df[
    (df["Category"] == "Investments") &
    (df["Type"] == "debit")
]["Amount"].sum()

investment_percentage = (investment / total_debit) * 100

if investment_percentage > 15:
    archetypes.append("📈 THE INVESTOR")



# LATE NIGHT SNACKER
food_delivery = df[
    (df["Category"] == "Food Delivery") &
    (df["Type"] == "debit")
]

late_night = food_delivery[
    (food_delivery["Hour"] >= 21) |
    (food_delivery["Hour"] <= 1)
]

late_percentage = (len(late_night) / len(food_delivery)) * 100

if late_percentage > 50:
    archetypes.append("🌙 THE LATE-NIGHT SNACKER")



# SUBSCRIPTIONS
subscription_count = df[
    df["Category"] == "Subscriptions"
]["Vendor"].nunique()

if subscription_count >= 5:
    archetypes.append("🎵 THE SUBSCRIPTION LOVER")



# YOLO
if savings_rate < 10:
    archetypes.append("💸 THE YOLO SPENDER")



# DISCIPLINED
if savings_rate > 40:
    archetypes.append("💰 THE DISCIPLINED SAVER")

In [343]:
print("=" * 50)
print("SPENDING ARCHETYPES")
print("=" * 50)

for archetype in archetypes:
    print(archetype)

==================================================
SPENDING ARCHETYPES
==================================================
🛍️ THE SHOPAHOLIC
💸 THE YOLO SPENDER

# Final SpendDNA Report

In [344]:
print("=" * 70)
print("                 SpendDNA REPORT - RAHUL SHARMA")
print("               6 Months Transaction Analysis")
print("=" * 70)

# Executive Summary
print("\nEXECUTIVE SUMMARY")
print("-" * 70)

print(f"Total Credits      : ₹{total_credit:,.2f}")
print(f"Total Debits       : ₹{total_debit:,.2f}")
print(f"Net Change         : ₹{net_change:,.2f}")
print(f"Savings Rate       : {savings_rate:.2f}%")
print(f"Transactions       : {len(df)}")
print(f"Unique Vendors     : {df['Vendor'].nunique()}")

# Top Categories
print("\nTOP 5 SPENDING CATEGORIES")
print("-" * 70)

for category, amount in top_categories.items():
    percentage = (amount / total_debit) * 100
    print(f"{category:<25} ₹{amount:>12,.2f} ({percentage:.2f}%)")

# Top Vendors
print("\nTOP 5 VENDORS")
print("-" * 70)

for vendor, amount in top_vendors.items():
    print(f"{vendor:<25} ₹{amount:>12,.2f}")

# Peak Spending Hour
print("\nTIME OF DAY ANALYSIS")
print("-" * 70)

print(f"Peak Spending Hour                 : {peak_hour}:00")
print(f"Late Night Food Delivery Orders    : {late_percentage:.2f}%")

# Monthly Trend
print("\nMONTHLY SPENDING TREND")
print("-" * 70)

print(monthly_spending.round(2))

# Anomalies
print("\nTOP 5 ANOMALOUS TRANSACTIONS")
print("-" * 70)

print(
    anomalies[
        ["Date", "Vendor", "Category", "Amount", "Z_Score"]
    ].head(5)
)

# Archetypes
print("\nSPENDING ARCHETYPES")
print("-" * 70)

for archetype in archetypes:
    print(archetype)

print("=" * 70)

======================================================================
                 SpendDNA REPORT - RAHUL SHARMA
               6 Months Transaction Analysis
======================================================================

EXECUTIVE SUMMARY
----------------------------------------------------------------------
Total Credits      : ₹509,774.00
Total Debits       : ₹1,678,901.00
Net Change         : ₹-1,169,127.00
Savings Rate       : -229.34%
Transactions       : 1310
Unique Vendors     : 39

TOP 5 SPENDING CATEGORIES
----------------------------------------------------------------------
E-Commerce                ₹  603,877.00 (35.97%)
Investments               ₹  248,160.00 (14.78%)
Food Delivery             ₹  150,839.00 (8.98%)
Restaurants               ₹  117,737.00 (7.01%)
Rent                      ₹  108,000.00 (6.43%)

TOP 5 VENDORS
----------------------------------------------------------------------
Amazon                    ₹  328,530.00
Zerodha                   ₹  210,000.00
Flipkart                  ₹  177,510.00
Rent                      ₹  108,000.00
Swiggy                    ₹   95,523.00

TIME OF DAY ANALYSIS
----------------------------------------------------------------------
Peak Spending Hour                 : 10:00
Late Night Food Delivery Orders    : 20.64%

MONTHLY SPENDING TREND
----------------------------------------------------------------------
Month              January  February     March    April      May      June  \
Category
Cafe                3690.0    4273.0    5448.0   6564.0   5668.0    5802.0
Cash Withdrawal     2000.0    5000.0    8000.0   5500.0   8000.0   17000.0
E-Commerce         98623.0   94011.0  108215.0  69219.0  95776.0  138033.0
Entertainment       1263.0     474.0    2418.0   2224.0      0.0    1914.0
Food Delivery      22633.0   23740.0   24803.0  27756.0  25408.0   26499.0
Fuel               30322.0    2079.0   26164.0  18718.0   9138.0    2882.0
Groceries          17649.0    8571.0    6971.0  13061.0  10336.0    7721.0
Investments        38432.0   15000.0   68644.0  54126.0  48628.0   23330.0
Personal Transfer   7523.0    4285.0    2415.0    663.0   3412.0    1541.0
Quick Commerce     11054.0   15177.0   13344.0  10557.0  11329.0    7519.0
Rent               18000.0   18000.0   18000.0  18000.0  18000.0   18000.0
Restaurants        16320.0   21772.0   28313.0   7711.0  22286.0   21335.0
Subscriptions       2767.0    4628.0    3509.0   2168.0   1844.0    3555.0
Transport          11005.0   10191.0    6857.0   9284.0  13141.0    6996.0
Utilities           9486.0    6870.0    7357.0   5831.0   4340.0   12790.0

Month              Growth (%)
Category
Cafe                    57.24
Cash Withdrawal        750.00
E-Commerce              39.96
Entertainment           51.54
Food Delivery           17.08
Fuel                   -90.50
Groceries              -56.25
Investments            -39.30
Personal Transfer      -79.52
Quick Commerce         -31.98
Rent                     0.00
Restaurants             30.73
Subscriptions           28.48
Transport              -36.43
Utilities               34.83

TOP 5 ANOMALOUS TRANSACTIONS
----------------------------------------------------------------------
           Date      Vendor     Category   Amount   Z_Score
1298 2024-06-26      Amazon   E-Commerce  22008.0  4.090349
269  2024-02-07      Amazon   E-Commerce  21986.0  4.085484
414  2024-02-26  Restaurant  Restaurants   8383.0  3.884639
475  2024-03-05      Amazon   E-Commerce  19917.0  3.627956
1271 2024-06-22  Restaurant  Restaurants   7935.0  3.627582

SPENDING ARCHETYPES
----------------------------------------------------------------------
🛍️ THE SHOPAHOLIC
💸 THE YOLO SPENDER
======================================================================

# Key Insights

### 1.
Food Delivery and Quick Commerce account for a significant portion of Rahul's spending, indicating a strong preference for online convenience.

### 2.
Rahul's spending behavior shows frequent late-night food orders, suggesting that most food purchases occur during late evening hours.

### 3.
Although Rahul regularly invests through platforms like Zerodha and Groww, discretionary spending on food, shopping, and entertainment forms a major share of total expenses.